### ISSUE TITLE
Bad location when viewport has POI set.

### ISSUE THREAD

**Issue by LProulx86** [nventive/Cartography#33]
## Expected Behavior
Must center the map on desire location with POI visible.

## Actual Behavior
Center is way off.

## Steps to Reproduce the Problem

1. Change Viewport with POI set.

## Specifications

- Version:  dynamicMap 0.2.0-dev.81 / not tested on staticMap
- Platform: Android/IOS
- Subsystem:

**Comment by carlh98** [comment]
@LProulx86 still relevant?
